name: deploy-to-skynet

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Skynet
        uses: skynetlabs/deploy-to-skynet-action@v2

        with:
          upload-dir: src
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/v2' && secrets.REGISTRY_SEED || '' }}
