name: deploy-to-skynet

on: workflow_dispatch
    
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Deploy to Skynet
        uses: skynetlabs/deploy-to-skynet-action@main

        with:
          upload-dir: src
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.REGISTRY_SEED || '' }}


